### ISSUE TITLE
Sourcemaps from npm reference source files not included in the package

### ISSUE THREAD

**Issue by vith** [sunknudsen/react-node-to-string#4]
`build/index.js` has `//# sourceMappingURL=index.js.map`
`build/index.js.map` has `"sources":["../src/index.ts"]`
but `src/index.ts` is not included, causing:

> WARNING in `../../node_modules/.pnpm/react-node-to-string@0.1.0_react@17.0.2/node_modules/react-node-to-string/build/index.js`
> Module Warning (from `../../node_modules/.pnpm/source-map-loader@3.0.1_webpack@5.69.0/node_modules/source-map-loader/dist/cjs.js`):
> Failed to parse source map from `'<workspace>/node_modules/.pnpm/react-node-to-string@0.1.0_react@17.0.2/node_modules/react-node-to-string/src/index.ts'` file: Error: ENOENT: no such file or directory, open `'<workspace>/node_modules/.pnpm/react-node-to-string@0.1.0_react@17.0.2/node_modules/react-node-to-string/src/index.ts'`

```console
❯ tree node_modules/.pnpm/react-node-to-string@0.1.0_react@17.0.2/
node_modules/.pnpm/react-node-to-string@0.1.0_react@17.0.2/
└── node_modules
    ├── react -> ../../react@17.0.2/node_modules/react
    └── react-node-to-string
        ├── build
        │   ├── index.d.ts
        │   ├── index.js
        │   └── index.js.map
        ├── LICENCE
        ├── package.json
        └── README.md

4 directories, 6 files
```

**Comment by sunknudsen** [comment]
Thanks for raising issue @vith… fixed by #7.
